In [49]:
print ("hello guys welcome to the workshop")

hello guys welcome to the workshop


In [14]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: C:\Users\ASUS\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [15]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: C:\Users\ASUS\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [16]:
pip install pandas


[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: C:\Users\ASUS\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [17]:
import numpy as np

In [18]:
arr = np.array([[2,3,4],[5,6,7]])

In [19]:
type(arr)

numpy.ndarray

In [20]:
print(arr)

[[2 3 4]
 [5 6 7]]


In [21]:
arr

array([[2, 3, 4],
       [5, 6, 7]])

In [22]:
arr.dtype

dtype('int32')

In [23]:
arr1=np.array([[2,3,4],[5,6,7]],np.int8)

In [24]:
arr1.dtype

dtype('int8')

In [25]:
arr1.shape

(2, 3)

In [30]:
arr.size

6

In [34]:
arr.len

AttributeError: 'numpy.ndarray' object has no attribute 'len'

In [ ]:
arr[0,2]

4

In [39]:
l=np.array({1,2,3})

In [40]:
l

array({1, 2, 3}, dtype=object)

In [42]:
type(l)

numpy.ndarray

In [43]:
print(l)

{1, 2, 3}


In [44]:
l.dtype

dtype('O')

In [45]:
z=np.zeros((3,4))

In [46]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [104]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
np.ones(10)*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [105]:
rng=np.arange(10)

In [106]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
s=np.linspace(1,10,10)

In [108]:
s

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [109]:
s=np.linspace(1,5,10)

In [110]:
s

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [111]:
emp1=np.empty([2,2])

In [112]:
emp1

array([[2.12199579e-314, 1.34534533e-311],
       [7.66789882e-321, 3.79442416e-321]])

In [113]:
emp=np.empty_like(emp1)

In [114]:
emp

array([[2.12199579e-314, 1.34534533e-311],
       [7.66789882e-321, 3.79442416e-321]])

In [115]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
arr1.sum(axis=0)

array([5, 7, 9])

In [118]:
arr1.sum(axis=1)

array([ 6, 15])

In [119]:
arr1.sum(axis=3)

AxisError: axis 3 is out of bounds for array of dimension 2

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[6,7,8]])

In [ ]:
arr1+arr2

array([[ 5,  7,  9],
       [10, 12, 14]])

In [ ]:
arr1*arr2

array([[ 4, 10, 18],
       [24, 35, 48]])

In [ ]:
arr1-arr2

array([[-3, -3, -3],
       [-2, -2, -2]])

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
arr1.max()

6

In [ ]:
arr1.min()

1

misc..

In [121]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

indexing

In [123]:
a = np.arange(1,25).reshape(4,-1)

In [124]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [125]:
a[1:4,2:]

array([[ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]])

In [126]:
a[3,1]

20

In [131]:
a[1:4,3:4]

array([[10],
       [16],
       [22]])

In [134]:
a[2:3,2:5]

array([[15, 16, 17]])

In [135]:
arr3=np.append(arr1,arr2)

In [136]:
arr3

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 6, 7, 8])