In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [2]:
iris = datasets.load_iris()
X = pd.DataFrame(iris.data)
X

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [4]:
f=pd.read_csv('iris.csv')

In [5]:
array = f.values
X = array[:,0:4]
Y = array[:,4]
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [6]:
X_train

array([[127, 6.2, 2.8, 4.8],
       [80, 5.7, 2.6, 3.5],
       [23, 4.6, 3.6, 1.0],
       [140, 6.9, 3.1, 5.4],
       [75, 6.4, 2.9, 4.3],
       [46, 4.8, 3.0, 1.4],
       [37, 5.5, 3.5, 1.3],
       [6, 5.4, 3.9, 1.7],
       [18, 5.1, 3.5, 1.4],
       [103, 7.1, 3.0, 5.9],
       [125, 6.7, 3.3, 5.7],
       [77, 6.8, 2.8, 4.8],
       [133, 6.4, 2.8, 5.6],
       [117, 6.5, 3.0, 5.5],
       [96, 5.7, 3.0, 4.2],
       [50, 5.0, 3.3, 1.4],
       [66, 6.7, 3.1, 4.4],
       [63, 6.0, 2.2, 4.0],
       [112, 6.4, 2.7, 5.3],
       [30, 4.7, 3.2, 1.6],
       [4, 4.6, 3.1, 1.5],
       [40, 5.1, 3.4, 1.5],
       [118, 7.7, 3.8, 6.7],
       [14, 4.3, 3.0, 1.1],
       [101, 6.3, 3.3, 6.0],
       [82, 5.5, 2.4, 3.7],
       [61, 5.0, 2.0, 3.5],
       [55, 6.5, 2.8, 4.6],
       [27, 5.0, 3.4, 1.6],
       [9, 4.4, 2.9, 1.4],
       [44, 5.0, 3.5, 1.6],
       [87, 6.7, 3.1, 4.7],
       [108, 7.3, 2.9, 6.3],
       [91, 5.5, 2.6, 4.4],
       [60, 5.2, 2.7, 3.9],
       [16, 5

In [7]:
Y_train

array([1.8, 1.0, 0.2, 2.1, 1.3, 0.3, 0.2, 0.4, 0.3, 2.1, 2.1, 1.4, 2.2,
       1.8, 1.2, 0.2, 1.4, 1.0, 1.9, 0.2, 0.2, 0.2, 2.2, 0.1, 2.5, 1.0,
       1.0, 1.5, 0.4, 0.2, 0.6, 1.5, 1.8, 1.2, 1.4, 0.4, 1.8, 0.2, 0.2,
       1.4, 2.0, 0.1, 2.2, 0.2, 1.3, 2.3, 1.4, 0.3, 1.4, 0.2, 2.0, 2.3,
       1.0, 0.2, 0.2, 1.3, 2.3, 0.2, 2.0, 2.4, 1.3, 0.4, 1.1, 0.2, 2.0,
       2.1, 0.2, 0.2, 2.5, 1.3, 1.9, 1.9, 1.0, 0.4, 0.4, 2.0, 0.2, 0.2,
       1.6, 2.3, 2.3, 1.3, 1.3, 0.1, 2.3, 0.2, 0.2, 1.5, 1.2, 2.1, 0.1,
       1.3, 1.5, 1.8, 2.1, 1.3, 1.5, 0.2, 1.6, 1.1, 0.4, 0.3, 0.3, 1.3,
       1.4, 0.2, 2.3, 1.8, 1.5, 2.4, 0.2, 2.0, 1.3, 1.5, 0.5, 1.9, 1.2,
       1.8, 1.0, 0.2], dtype=object)

In [8]:
X_validation

array([[150, 5.9, 3.0, 5.1],
       [85, 5.4, 3.0, 4.5],
       [41, 5.0, 3.5, 1.3],
       [67, 5.6, 3.0, 4.5],
       [107, 4.9, 2.5, 4.5],
       [42, 4.5, 2.3, 1.3],
       [53, 6.9, 3.1, 4.9],
       [95, 5.6, 2.7, 4.2],
       [12, 4.8, 3.4, 1.6],
       [52, 6.4, 3.2, 4.5],
       [78, 6.7, 3.0, 5.0],
       [86, 6.0, 3.4, 4.5],
       [33, 5.2, 4.1, 1.5],
       [110, 7.2, 3.6, 6.1],
       [29, 5.2, 3.4, 1.4],
       [71, 5.9, 3.2, 4.8],
       [109, 6.7, 2.5, 5.8],
       [138, 6.4, 3.1, 5.5],
       [47, 5.1, 3.8, 1.6],
       [38, 4.9, 3.1, 1.5],
       [83, 5.8, 2.7, 3.9],
       [121, 6.9, 3.2, 5.7],
       [64, 6.1, 2.9, 4.7],
       [120, 6.0, 2.2, 5.0],
       [130, 7.2, 3.0, 5.8],
       [139, 6.0, 3.0, 4.8],
       [98, 6.2, 2.9, 4.3],
       [81, 5.5, 2.4, 3.8],
       [102, 5.8, 2.7, 5.1],
       [141, 6.7, 3.1, 5.6]], dtype=object)

In [9]:
Y_validation

array([1.8, 1.5, 0.3, 1.5, 1.7, 0.3, 1.5, 1.3, 0.2, 1.5, 1.7, 1.6, 0.1,
       2.5, 0.2, 1.8, 1.8, 1.8, 0.2, 0.1, 1.2, 2.3, 1.4, 1.5, 1.6, 1.8,
       1.3, 1.1, 1.9, 2.4], dtype=object)

In [10]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: C:\Users\ASUS\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
pip install seaborn


[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: C:\Users\ASUS\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip



     ------------------------------------ 285.1/285.1 kB 978.2 kB/s eta 0:00:00
